name: Job Status Restoration Action

description: Restore job status

inputs:
  cache-key:
    description: a unique key for the cache
    required: true
    type: string

  files:
    description: a list of additional files or directories to be restored
    required: false
    type: string

outputs:
  cache-key:
    description: an pass-through cache-key from the input

  cache-hit:
    description: whether the job status is restored or not

runs:
  using: node20
  main: main.js
