name: Job Cache Saving Action

description: Cache job status

inputs:
  cache-key:
    required: true
    type: string

  job-status:
    required: false
    type: string
    default: ${{ job.status }}

  github-token:
    required: false
    type: string
    default: ${{ github.token }}

runs:
  using: node20
  main: main.js
