name: Job Status Saving Action

description: Cache job status

inputs:
  cache-key:
    description: a unique key for the cache
    type: string

  files:
    description: a list of additional files or directories to be cached
    type: string

  job-status:
    type: string
    default: ${{ job.status }}

  github-token:
    type: string
    default: ${{ github.token }}

runs:
  using: node20
  main: main.js
