on:
  push:

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: exit 0

      - if: ${{ always() }}
        uses: ./save
        id: cache
        with:
          cache-key: success-${{ github.run_number }}

  failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: exit 1

      - if: ${{ always() }}
        uses: ./save
        id: cache
        with:
          cache-key: failure-${{ github.run_number }}

  cache-hit-success:
    runs-on: ubuntu-latest
    needs: success
    steps:
      - uses: actions/checkout@v3

      - uses: ./restore
        id: cache
        with:
          cache-key: success-${{ github.run_number }}

      - if: ${{ always() }}
        run: echo "${{ steps.cache.outputs.cache-hit }}"

  cache-hit-failure:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: failure
    steps:
      - uses: actions/checkout@v3

      - uses: ./restore
        id: cache
        with:
          cache-key: failure-${{ github.run_number }}

      - if: ${{ always() }}
        run: echo "${{ steps.cache.outputs.cache-hit }}"

  cache-miss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./restore
        id: cache
        with:
          cache-key: miss-${{ github.run_number }}

      - if: ${{ always() }}
        run: echo "${{ steps.cache.outputs.cache-hit }}"
